### ISSUE TITLE
Trying to use `get_oeis_factors` crashes backscope

### ISSUE THREAD

**Issue by liammulh** [numberscope/frontscope#170]
If I go to https://numberscope.colorado.edu/api/get_oeis_factors/A000040/1000 backscope crashes with a log that looks like what's in the details below. (I couldn't post the whole log because otherwise the body of this issue would exceed GitHub's maximum character count.)

<details>
<summary>Log</summary>

```
Oct 11 14:42:28 numberscope bash[1294341]: [2022-10-11 14:42:28 -0600] [1294341] [INFO] Starting gunicorn 20.1.0
Oct 11 14:42:28 numberscope bash[1294341]: [2022-10-11 14:42:28 -0600] [1294341] [INFO] Listening at: unix:/home/scope/repos/backscope/backscope.sock (1294341)
Oct 11 14:42:28 numberscope bash[1294341]: [2022-10-11 14:42:28 -0600] [1294341] [INFO] Using worker: sync
Oct 11 14:42:28 numberscope bash[1294342]: [2022-10-11 14:42:28 -0600] [1294342] [INFO] Booting worker with pid: 1294342
Oct 11 14:42:28 numberscope bash[1294343]: [2022-10-11 14:42:28 -0600] [1294343] [INFO] Booting worker with pid: 1294343
Oct 11 14:42:28 numberscope bash[1294344]: [2022-10-11 14:42:28 -0600] [1294344] [INFO] Booting worker with pid: 1294344
Oct 11 14:43:05 numberscope bash[1294341]: [2022-10-11 14:43:05 -0600] [1294341] [CRITICAL] WORKER TIMEOUT (pid:1294343)
Oct 11 14:43:05 numberscope bash[1294343]: ------------------------------------------------------------------------
Oct 11 14:43:05 numberscope bash[1294343]: /home/scope/repos/backscope/.venv/lib/python3.9/site-packages/cysignals/signals.cpython-39-x86_64-linux-gnu.so(+0x8938)[0x7f405e8fa938]
Oct 11 14:43:05 numberscope bash[1294343]: /home/scope/repos/backscope/.venv/lib/python3.9/site-packages/cysignals/signals.cpython-39-x86_64-linux-gnu.so(+0x89d9)[0x7f405e8fa9d9]
Oct 11 14:43:05 numberscope bash[1294343]: /home/scope/repos/backscope/.venv/lib/python3.9/site-packages/cysignals/signals.cpython-39-x86_64-linux-gnu.so(+0xbc0f)[0x7f405e8fdc0f]

[...]

Oct 11 14:43:05 numberscope bash[1294343]: ------------------------------------------------------------------------
Oct 11 14:43:05 numberscope bash[1294427]: Attaching gdb to process id 1294343.
Oct 11 14:43:06 numberscope bash[1294427]: GNU gdb (Debian 10.1-1.7) 10.1.90.20210103-git
Oct 11 14:43:06 numberscope bash[1294427]: Copyright (C) 2021 Free Software Foundation, Inc.
Oct 11 14:43:06 numberscope bash[1294427]: License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
Oct 11 14:43:06 numberscope bash[1294427]: This is free software: you are free to change and redistribute it.
Oct 11 14:43:06 numberscope bash[1294427]: There is NO WARRANTY, to the extent permitted by law.
Oct 11 14:43:06 numberscope bash[1294427]: Type "show copying" and "show warranty" for details.
Oct 11 14:43:06 numberscope bash[1294427]: This GDB was configured as "x86_64-linux-gnu".
Oct 11 14:43:06 numberscope bash[1294427]: Type "show configuration" for configuration details.
Oct 11 14:43:06 numberscope bash[1294427]: For bug reporting instructions, please see:
Oct 11 14:43:06 numberscope bash[1294427]: <https://www.gnu.org/software/gdb/bugs/>.
Oct 11 14:43:06 numberscope bash[1294427]: Find the GDB manual and other documentation resources online at:
Oct 11 14:43:06 numberscope bash[1294427]:     <http://www.gnu.org/software/gdb/documentation/>.
Oct 11 14:43:06 numberscope bash[1294427]: For help, type "help".
Oct 11 14:43:06 numberscope bash[1294427]: Type "apropos word" to search for commands related to "word".
Oct 11 14:43:06 numberscope bash[1294427]: (No debugging symbols found in /usr/bin/python3.9)
Oct 11 14:43:06 numberscope bash[1294427]: [Thread debugging using libthread_db enabled]
Oct 11 14:43:06 numberscope bash[1294427]: Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Oct 11 14:43:06 numberscope bash[1294427]: (No debugging symbols found in /lib/x86_64-linux-gnu/libexpat.so.1)
Oct 11 14:43:06 numberscope bash[1294427]: (No debugging symbols found in /lib/x86_64-linux-gnu/libz.so.1)

[...]

Oct 11 14:43:06 numberscope bash[1294427]: Stack backtrace
Oct 11 14:43:06 numberscope bash[1294427]: ---------------
Oct 11 14:43:06 numberscope bash[1294427]:     stat_loc=stat_loc@entry=0x0, options=options@entry=0,
Oct 11 14:43:06 numberscope bash[1294427]:     usage=usage@entry=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:27
Oct 11 14:43:06 numberscope bash[1294427]: No locals.
Oct 11 14:43:06 numberscope bash[1294427]: #1  0x00007f40770cbb47 in __GI___waitpid (pid=<optimized out>,
Oct 11 14:43:06 numberscope bash[1294427]:     stat_loc=stat_loc@entry=0x0, options=options@entry=0) at waitpid.c:38
Oct 11 14:43:06 numberscope bash[1294427]: No locals.
Oct 11 14:43:06 numberscope bash[1294427]: #2  0x00007f405e8f93f3 in print_enhanced_backtrace ()
Oct 11 14:43:06 numberscope bash[1294427]:     at build/src/cysignals/implementation.c:586
Oct 11 14:43:06 numberscope bash[1294427]:         parent_pid = 1294343
Oct 11 14:43:06 numberscope bash[1294427]:         pid = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]: #3  0x00007f405e8faa16 in sigdie (sig=sig@entry=6,
Oct 11 14:43:06 numberscope bash[1294427]:     s=s@entry=0x7f405e902af0 "Unhandled SIGABRT: An abort() occurred.")
Oct 11 14:43:06 numberscope bash[1294427]:     at build/src/cysignals/implementation.c:612
Oct 11 14:43:06 numberscope bash[1294427]: No locals.
Oct 11 14:43:06 numberscope bash[1294427]: #4  0x00007f405e8fdc0f in sigdie_for_sig (inside=0, sig=6)
Oct 11 14:43:06 numberscope bash[1294427]:     at build/src/cysignals/implementation.c:175
Oct 11 14:43:06 numberscope bash[1294427]: No locals.
Oct 11 14:43:06 numberscope bash[1294427]: #5  cysigs_signal_handler (sig=6) at build/src/cysignals/implementation.c:278
Oct 11 14:43:06 numberscope bash[1294427]:         inside = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]: #6  <signal handler called>
Oct 11 14:43:06 numberscope bash[1294427]: No locals.
Oct 11 14:43:06 numberscope bash[1294427]: #7  __libc_read (nbytes=5, buf=0x236f823, fd=12)
Oct 11 14:43:06 numberscope bash[1294427]:     at ../sysdeps/unix/sysv/linux/read.c:26
Oct 11 14:43:06 numberscope bash[1294427]:         resultvar = 18446744073709551612
Oct 11 14:43:06 numberscope bash[1294427]:         sc_cancel_oldtype = 0
Oct 11 14:43:06 numberscope bash[1294427]:         __arg3 = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         _a2 = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         sc_ret = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         __value = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         __arg1 = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         _a3 = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         resultvar = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         resultvar = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         __arg2 = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         _a1 = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]: #8  __libc_read (fd=12, buf=0x236f823, nbytes=5)
Oct 11 14:43:06 numberscope bash[1294427]:     at ../sysdeps/unix/sysv/linux/read.c:24
Oct 11 14:43:06 numberscope bash[1294427]: No locals.
Oct 11 14:43:06 numberscope bash[1294427]: #9  0x00007f407639c545 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
Oct 11 14:43:06 numberscope bash[1294427]: No symbol table info available.
Oct 11 14:43:06 numberscope bash[1294427]: #10 0x00007f407639775a in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
Oct 11 14:43:06 numberscope bash[1294427]: No symbol table info available.
Oct 11 14:43:06 numberscope bash[1294427]: #11 0x00007f4076396604 in ?? () from /lib/x86_64-linux-gnu/libcrypto.so.1.1
Oct 11 14:43:06 numberscope bash[1294427]: No symbol table info available.

[...]

Oct 11 14:43:06 numberscope bash[1294427]: #131 0x00007f4077026d0a in __libc_start_main (main=0x5ea6b0, argc=9,
Oct 11 14:43:06 numberscope bash[1294427]:     argv=0x7ffc6a87fa58, init=<optimized out>, fini=<optimized out>,
Oct 11 14:43:06 numberscope bash[1294427]:     rtld_fini=<optimized out>, stack_end=0x7ffc6a87fa48)
Oct 11 14:43:06 numberscope bash[1294427]:     at ../csu/libc-start.c:308
Oct 11 14:43:06 numberscope bash[1294427]:         self = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         result = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]:         unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, 2404890529182144978,
Oct 11 14:43:06 numberscope bash[1294427]:                 6202816, 0, 0, 0, -2402891493661845038,
Oct 11 14:43:06 numberscope bash[1294427]:                 -2315116419985155630}, mask_was_saved = 0}}, priv = {pad = {
Oct 11 14:43:06 numberscope bash[1294427]:               0x0, 0x0, 0x9, 0x7ffc6a87fa58}, data = {prev = 0x0,
Oct 11 14:43:06 numberscope bash[1294427]:               cleanup = 0x0, canceltype = 9}}}
Oct 11 14:43:06 numberscope bash[1294427]:         not_first_call = <optimized out>
Oct 11 14:43:06 numberscope bash[1294427]: #132 0x00000000005ea5ea in _start ()
Oct 11 14:43:06 numberscope bash[1294427]: No symbol table info available.
Oct 11 14:43:06 numberscope bash[1294427]: >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
Oct 11 14:43:06 numberscope bash[1294427]: Cython backtrace
Oct 11 14:43:06 numberscope bash[1294427]: ----------------
Oct 11 14:43:06 numberscope bash[1294427]: #0  0x00007f40770cbb70 in __GI___wait4 () at ./posix/../sysdeps/unix/sysv/linux/wait4.c:27
Oct 11 14:43:06 numberscope bash[1294427]: #1  0x00007f40770cbb40 in __GI___waitpid () at ./posix/waitpid.c:38
Oct 11 14:43:06 numberscope bash[1294427]: #2  0x00007f405e8f9390 in print_enhanced_backtrace () at /project/build/src/cysignals/implementation.c:586
Oct 11 14:43:06 numberscope bash[1294427]: #3  0x00007f405e8fa9a0 in sigdie () at /project/build/src/cysignals/implementation.c:612
Oct 11 14:43:06 numberscope bash[1294427]: #4  0x00007f405e8fd9fc in sigdie_for_sig () at /project/build/src/cysignals/implementation.c:175
Oct 11 14:43:06 numberscope bash[1294427]: #5  0x00007f405e8fd9e0 in cysigs_signal_handler () at /project/build/src/cysignals/implementation.c:278
Oct 11 14:43:06 numberscope bash[1294427]: #6  0x00007f40773c7070 in __restore_rt ()
Oct 11 14:43:06 numberscope bash[1294427]: #7  0x00007f4077387072 in __libc_read () at ./nptl/../sysdeps/unix/sysv/linux/read.c:26
Oct 11 14:43:06 numberscope bash[1294427]: #8  0x00007f4077387040 in __libc_read () at ./nptl/../sysdeps/unix/sysv/linux/read.c:24
Oct 11 14:43:06 numberscope bash[1294427]: #9  0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #10 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #11 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #12 0x00007f4076396bb0 in BIO_read ()
Oct 11 14:43:06 numberscope bash[1294427]: #13 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #14 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #15 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #16 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #17 0x00007f4076603580 in SSL_read ()
Oct 11 14:43:06 numberscope bash[1294427]: #18 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #19 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #20 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #21 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #22 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #23 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #24 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #25 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #26 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #27 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #28 0x00000000005308f0 in PyObject_VectorcallMethod ()
Oct 11 14:43:06 numberscope bash[1294427]: #29 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #30 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #31 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #32 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #33 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #34 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #35 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #36 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #37 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #38 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #39 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #40 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #41 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #42 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #43 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #44 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #45 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #46 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #47 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #48 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #49 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #50 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #51 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #52 0x000000000053c2a0 in PyObject_Call ()
Oct 11 14:43:06 numberscope bash[1294427]: #53 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #54 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #55 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #56 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #57 0x000000000053c2a0 in PyObject_Call ()
Oct 11 14:43:06 numberscope bash[1294427]: #58 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #59 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #60 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #61 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #62 0x000000000053c2a0 in PyObject_Call ()
Oct 11 14:43:06 numberscope bash[1294427]: #63 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #64 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #65 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #66 0x000000000053c2a0 in PyObject_Call ()
Oct 11 14:43:06 numberscope bash[1294427]: #67 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #68 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #69 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #70 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #71 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #72 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #73 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #74 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #75 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #76 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #77 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #78 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #79 0x000000000053c2a0 in PyObject_Call ()
Oct 11 14:43:06 numberscope bash[1294427]: #80 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #81 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #82 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #83 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #84 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #85 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #86 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #87 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #88 0x000000000051cf40 in _PyObject_FastCallDictTstate ()
Oct 11 14:43:06 numberscope bash[1294427]: #89 0x00000000005384f0 in _PyObject_Call_Prepend ()
Oct 11 14:43:06 numberscope bash[1294427]: #90 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #91 0x000000000051d500 in _PyObject_MakeTpCall ()
Oct 11 14:43:06 numberscope bash[1294427]: #92 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #93 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #94 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #95 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #96 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #97 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #98 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #99 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #100 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #101 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #102 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #103 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #104 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #105 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #106 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #107 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #108 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #109 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #110 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #111 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #112 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #113 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #114 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #115 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #116 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #117 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #118 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #119 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #120 0x00000000005289c0 in _PyFunction_Vectorcall ()
Oct 11 14:43:06 numberscope bash[1294427]: #121 0x0000000000511a90 in _PyEval_EvalFrameDefault ()
Oct 11 14:43:06 numberscope bash[1294427]: #122 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #123 0x0000000000510450 in _PyEval_EvalCodeWithName ()
Oct 11 14:43:06 numberscope bash[1294427]: #124 0x00000000005f5bc0 in PyEval_EvalCode ()
Oct 11 14:43:06 numberscope bash[1294427]: #125 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #126 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #127 0x0000000000000000 in ?? ()
Oct 11 14:43:06 numberscope bash[1294427]: #128 0x0000000000619680 in PyRun_SimpleFileExFlags ()
Oct 11 14:43:06 numberscope bash[1294427]: #129 0x000000000060d230 in Py_RunMain ()
Oct 11 14:43:06 numberscope bash[1294427]: #130 0x00000000005ea6c0 in Py_BytesMain ()
Oct 11 14:43:06 numberscope bash[1294427]: #131 0x00007f4077026c20 in __libc_start_main () at ./csu/../csu/libc-start.c:308
Oct 11 14:43:06 numberscope bash[1294427]: #132 0x00000000005ea5c0 in _start ()
Oct 11 14:43:06 numberscope bash[1294427]: [Inferior 1 (process 1294343) detached]
Oct 11 14:43:06 numberscope bash[1294427]: gdb: warning: Couldn't determine a path for the index cache directory.
Oct 11 14:43:06 numberscope bash[1294427]: 27        ../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
Oct 11 14:43:06 numberscope bash[1294427]: Saved trace to /home/scope/repos/backscope/cysignals_crash_logs/crash_fio73rcb.log
Oct 11 14:43:06 numberscope bash[1294343]: ------------------------------------------------------------------------
Oct 11 14:43:06 numberscope bash[1294343]: Unhandled SIGABRT: An abort() occurred.
Oct 11 14:43:06 numberscope bash[1294343]: This probably occurred because a *compiled* module has a bug
Oct 11 14:43:06 numberscope bash[1294343]: in it and is not properly wrapped with sig_on(), sig_off().
Oct 11 14:43:06 numberscope bash[1294343]: Python will now terminate.
Oct 11 14:43:06 numberscope bash[1294343]: ------------------------------------------------------------------------
Oct 11 14:43:06 numberscope bash[1294341]: [2022-10-11 14:43:06 -0600] [1294341] [WARNING] Worker with pid 1294343 was terminated due to signal 6
Oct 11 14:43:06 numberscope bash[1294441]: [2022-10-11 14:43:06 -0600] [1294441] [INFO] Booting worker with pid: 1294441
```

</details>

To see this log, `sudo journalctl -u backscope`.

**Comment by gwhitney** [comment]
I believe this is solved by recompiling cypari on the server, and it seems like this should be a backscope issue anyway, so closing this
